### PR TITLE
Update interface to remove strings in favor of char* buffers

### PR DESCRIPTION
**Pull request by ciband**
This is my first initial pass through the code to remove the usage of dynamic strings where it made sense (i.e. for non-dynamic data).  Interface changed to allow for static buffers to be passed in to functions where the data could be dynamic (e.g. description() functions).  The JSON classes are still using string due to the dynamic nature of JSON data.  All unit tests pass except for certain sections where large strings are involved.  This issue will be fixed in future changes when bigint is incorporated.  A few other bug fixes and optimizations were made as well.

### CODE REVIEW

**Comment by sleepdefic1t** [comment]
Great work, @ciband 

Everything compiles.
Using verbose output during compile, I do get the following warnings though:

```cpp
In file included from .../Arduino/libraries/Ark-Cpp/src/types/types.h:6:0,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:9,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/types/address.h:32:34: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
  const char* const description() const { return value_; }
                                  ^
In file included from .../Arduino/libraries/Ark-Cpp/src/types/types.h:7:0,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:9,
                 from.../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/types/balance.h:83:29: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     const char* const ark() const { return ark_; }
                             ^
.../Arduino/libraries/Ark-Cpp/src/types/balance.h:84:34: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     const char* const arktoshi() const { return arktoshi_; }
                                  ^
.../Arduino/libraries/Ark-Cpp/src/types/balance.h: In constructor 'Balance::Balance(const char*)':
.../Arduino/libraries/Ark-Cpp/src/types/balance.h:45:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (auto i = 0; i < strlen(balanceStr); ++i) {
                                         ^
.../Arduino/libraries/Ark-Cpp/src/types/balance.h: In member function 'Balance& Balance::operator=(const Balance&)':
.../Arduino/libraries/Ark-Cpp/src/types/balance.h:65:2: warning: no return statement in function returning non-void [-Wreturn-type]
  }
  ^
.../Arduino/libraries/Ark-Cpp/src/types/balance.h: In member function 'Balance& Balance::operator=(Balance&&)':
.../Arduino/libraries/Ark-Cpp/src/types/balance.h:80:2: warning: no return statement in function returning non-void [-Wreturn-type]
  }
  ^
.../Arduino/libraries/Ark-Cpp/src/types/balance.h: In member function 'void Balance::setArk(const char*)':
.../Arduino/libraries/Ark-Cpp/src/types/balance.h:96:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (auto i = 1; i <= num_zero_pad; ++i)
                               ^
.../Arduino/libraries/Ark-Cpp/src/types/balance.h:100:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (auto i = 0; i <= num_zero_pad + 1; ++i) 
                                              ^
.../Arduino/libraries/Ark-Cpp/src/types/balance.h:109:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (i < length - DECIMAL_PLACES) { this->ark_[i] = balanceStr[i]; }
                              ^
.../Arduino/libraries/Ark-Cpp/src/types/balance.h:110:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (i == length - DECIMAL_PLACES) { this->ark_[i] = '.'; }
                               ^
.../Arduino/libraries/Ark-Cpp/src/types/balance.h:111:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (i > length - DECIMAL_PLACES && i <= length) { this->ark_[i] = balanceStr[i - 1]; }
                              ^
.../Arduino/libraries/Ark-Cpp/src/types/balance.h:111:53: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (i > length - DECIMAL_PLACES && i <= length) { this->ark_[i] = balanceStr[i - 1]; }
                                                     ^
In file included from .../Arduino/libraries/Ark-Cpp/src/types/types.h:8:0,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:9,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/types/hash.h: At global scope:
.../Arduino/libraries/Ark-Cpp/src/types/hash.h:35:35: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   const char* const description() const { return value_; }
                                   ^
In file included from .../Arduino/libraries/Ark-Cpp/src/types/types.h:9:0,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:9,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/types/publickey.h:39:41: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
         const char* const description() const { return value_; };      
                                         ^
In file included from .../Arduino/libraries/Ark-Cpp/src/types/types.h:10:0,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:9,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/types/signature.h:33:37: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     const char* const description() const { return value_; };      
                                     ^
In file included from .../Arduino/libraries/Ark-Cpp/src/constants/../model/model.h:6:0,
                 from .../Arduino/libraries/Ark-Cpp/src/constants/constants.h:6,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:10,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/constants/../model/account.h:68:6: warning: unused parameter 'len' [-Wunused-parameter]
 void ARK::Account::Account::description(char* const buf, size_t len)
      ^
In file included from .../Arduino/libraries/Ark-Cpp/src/constants/../model/model.h:7:0,
                 from .../Arduino/libraries/Ark-Cpp/src/constants/constants.h:6,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:10,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/constants/../model/block.h: In member function 'void ARK::Block::description(char*, size_t)':
.../Arduino/libraries/Ark-Cpp/src/constants/../model/block.h:130:50: warning: format '%d' expects argument of type 'int', but argument 3 has type 'char*' [-Wformat=]
     sprintf(buf + strlen(buf), "%d", this->height);
                                                  ^
.../Arduino/libraries/Ark-Cpp/src/constants/../model/block.h:130:50: warning: format '%d' expects argument of type 'int', but argument 3 has type 'char*' [-Wformat=]
.../Arduino/libraries/Ark-Cpp/src/constants/../model/block.h:134:64: warning: format '%d' expects argument of type 'int', but argument 3 has type 'char*' [-Wformat=]
     sprintf(buf + strlen(buf), "%d", this->numberOfTransactions);
                                                                ^
.../Arduino/libraries/Ark-Cpp/src/constants/../model/block.h:134:64: warning: format '%d' expects argument of type 'int', but argument 3 has type 'char*' [-Wformat=]
.../Arduino/libraries/Ark-Cpp/src/constants/../model/block.h: At global scope:
.../Arduino/libraries/Ark-Cpp/src/constants/../model/block.h:120:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::Block::Block::description(char* const buf, size_t size)
      ^
In file included from .../Arduino/libraries/Ark-Cpp/src/constants/../model/model.h:8:0,
                 from .../Arduino/libraries/Ark-Cpp/src/constants/constants.h:6,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:10,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/constants/../model/currency.h:22:14: warning: unused parameter 'size' [-Wunused-parameter]
         void description(char* const buf, size_t size) {
              ^
In file included from .../Arduino/libraries/Ark-Cpp/src/constants/../model/model.h:9:0,
                 from .../Arduino/libraries/Ark-Cpp/src/constants/constants.h:6,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:10,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/constants/../model/delegate.h:68:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::Delegate::Delegate::description(char* const buf, size_t size) const
      ^
In file included from .../Arduino/libraries/Ark-Cpp/src/constants/../model/model.h:10:0,
                 from .../Arduino/libraries/Ark-Cpp/src/constants/constants.h:6,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:10,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/constants/../model/fees.h:40:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::Fees::Fees::description(char* const buf, size_t size)
      ^
In file included from .../Arduino/libraries/Ark-Cpp/src/constants/../model/model.h:11:0,
                 from .../Arduino/libraries/Ark-Cpp/src/constants/constants.h:6,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:10,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/constants/../model/network.h:79:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::Network::Network::description(char* const buf, size_t size) const {
      ^
In file included from .../Arduino/libraries/Ark-Cpp/src/constants/../model/model.h:12:0,
                 from .../Arduino/libraries/Ark-Cpp/src/constants/constants.h:6,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:10,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/constants/../model/peer.h:49:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::Peer::Peer::description(char* const buf, size_t size) {
      ^
In file included from .../Arduino/libraries/Ark-Cpp/src/constants/../model/model.h:13:0,
                 from .../Arduino/libraries/Ark-Cpp/src/constants/constants.h:6,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:10,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/constants/../model/transaction.h:81:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::Transaction::Transaction::description(char* const buf, size_t size) {
      ^
In file included from .../Arduino/libraries/Ark-Cpp/src/constants/../model/model.h:15:0,
                 from .../Arduino/libraries/Ark-Cpp/src/constants/constants.h:6,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:10,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/constants/../model/voter.h:40:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::Voter::Voter::description(char* const buf, size_t size) {
      ^
In file included from .../Arduino/libraries/Ark-Cpp/src/constants/constants.h:9:0,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:10,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/constants/networks.h:47:31: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
  const char* const randomPeer()
                               ^
.../Arduino/libraries/Ark-Cpp/src/constants/networks.h:107:31: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
  const char* const randomPeer()
                               ^
In file included from .../Arduino/libraries/Ark-Cpp/src/api/accountable/accountable.h:6:0,
                 from .../Arduino/libraries/Ark-Cpp/src/api/api.h:11,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:13,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/api/accountable/account_respondable.h:41:8: warning: unused parameter 'size' [-Wunused-parameter]
   void ARK::API::Account::Respondable::Balances::description(char* const buf, size_t size)
        ^
In file included from .../Arduino/libraries/Ark-Cpp/src/api/blockable/blockable.h:6:0,
                 from .../Arduino/libraries/Ark-Cpp/src/api/api.h:12,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:13,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/api/blockable/block_respondable.h:81:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::API::Block::Respondable::Status::description(char* const buf, size_t size)
      ^
.../Arduino/libraries/Ark-Cpp/src/api/blockable/block_respondable.h:109:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::API::Block::Respondable::Height::description(char* const buf, size_t size)
      ^
In file included from .../Arduino/libraries/Ark-Cpp/src/api/delegatable/delegatable.h:6:0,
                 from .../Arduino/libraries/Ark-Cpp/src/api/api.h:13,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:13,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/api/delegatable/delegate_respondable.h:113:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::API::Delegate::Respondable::Search::description(char* const buf, size_t size)
      ^
.../Arduino/libraries/Ark-Cpp/src/api/delegatable/delegate_respondable.h: In member function 'void ARK::API::Delegate::Respondable::Voters::description(char*, size_t)':
.../Arduino/libraries/Ark-Cpp/src/api/delegatable/delegate_respondable.h:140:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < this->count; i++) {
                               ^
.../Arduino/libraries/Ark-Cpp/src/api/delegatable/delegate_respondable.h: At global scope:
.../Arduino/libraries/Ark-Cpp/src/api/delegatable/delegate_respondable.h:161:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::API::Delegate::Respondable::ForgedByAccount::description(char* const buf, size_t size)
      ^
.../Arduino/libraries/Ark-Cpp/src/api/delegatable/delegate_respondable.h:194:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::API::Delegate::Respondable::NextForgers::description(char* const buf, size_t size)
      ^
In file included from .../Arduino/libraries/Ark-Cpp/src/api/loadable/loadable.h:6:0,
                 from .../Arduino/libraries/Ark-Cpp/src/api/api.h:14,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:13,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/api/loadable/loader_respondable.h:76:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::API::Loader::Respondable::Status::description(char* const buf, size_t size)
      ^
.../Arduino/libraries/Ark-Cpp/src/api/loadable/loader_respondable.h: In member function 'void ARK::API::Loader::Respondable::Sync::description(char*, size_t)':
.../Arduino/libraries/Ark-Cpp/src/api/loadable/loader_respondable.h:102:10: warning: unused variable 'len' [-Wunused-variable]
     auto len = strlen(buf);
          ^
.../Arduino/libraries/Ark-Cpp/src/api/loadable/loader_respondable.h: At global scope:
.../Arduino/libraries/Ark-Cpp/src/api/loadable/loader_respondable.h:97:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::API::Loader::Respondable::Sync::description(char* const buf, size_t size)
      ^
In file included from .../Arduino/libraries/Ark-Cpp/src/api/peerable/peerable.h:6:0,
                 from .../Arduino/libraries/Ark-Cpp/src/api/api.h:16,
                 from .../Arduino/libraries/Ark-Cpp/ark.h:13,
                 from .../Arduino/sketch_feb12a/sketch_feb12a.ino:2:
.../Arduino/libraries/Ark-Cpp/src/api/peerable/peer_respondable.h:60:6: warning: unused parameter 'size' [-Wunused-parameter]
 void ARK::API::Peer::Respondable::Version::description(char* const buf, size_t size) {
```

Mostly signed/unsigned comparison warnings,  
 and unused var (will be fixed with a printable description update),

##

Otherwise `const char* const ark() const { return ark_; }` throws warning.  
`const char* description() const { return value_; }` compiles OK, no warnings.



`balance.h`
```cpp
    const char* const ark() const { return ark_; }
    const char* const arktoshi() const { return arktoshi_; }
```  
```cpp
.../Arduino/libraries/Ark-Cpp/src/types/balance.h:83:29: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     const char* const ark() const { return ark_; }
                             ^
.../Arduino/libraries/Ark-Cpp/src/types/balance.h:84:34: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     const char* const arktoshi() const { return arktoshi_; }
```

The following compiles, no warnings.
```cpp
    const char* ark() const { return ark_; }
    const char* arktoshi() const { return arktoshi_; }
```


Which follows pretty much the same fix for the other warnings of this type involving `const`.

##

Do you want to fix these warnings first?
or if you're wrapped up in crypto classes, I can merge and fix these myself.

**Comment by ciband** [comment]
I can take care of them.  

The pointer const on the return type supprised me.  I actually have a feature branch with cmake support compilingunder Windows, and I saw most of those warnings. Was wondering why I didn’t see them on arduino. Now I know why.  Must tweak arduino ide settings. 

I’ll get this turned around.

**Comment by sleepdefic1t** [comment]
screen shot 2018-02-12 at 8 32 31 am

**Comment by ciband** [comment]
Ok, I think I did the updates correctly.  Still fairly new at the GitHub PR thing.  Compiled a couple of the playground tests and have no warnings now.  Please let me know if you find anything else.  Thank you.

**Pull request merged**
